<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style>
    table, th, td {
      border:2px solid black;
      border-collapse: collapse;
      padding: 20px;
    }
  </style>
  </head>
  <body>
    <center>
      <table>
        <legend>JEFES</legend>
        <tr>
          <th>Numero Empleado</th>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Genero</th>
          <th>Fecha Nacimiento</th>
          <th>Fecha de alta en la empresa</th>
        </tr>
        <?php foreach ($jefes->fetchAll() as $row) { ?>
          <tr>
            <td><?php echo $row['num']; ?></td>
            <td><?php echo $row['first_name']; ?></td>
            <td><?php echo $row['last_name']; ?></td>
            <td><?php echo $row['gender']; ?></td>
            <td><?php echo $row['birth_date']; ?></td>
            <td><?php echo $row['hire_date']; ?></td>
          </tr>
        <?php } ?>
      </table><br><br>
      <table>
        <legend>Empleados</legend>
        <tr>
          <th>Numero Empleado</th>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Genero</th>
          <th>Fecha Nacimiento</th>
          <th>Fecha de alta en la empresa</th>
        </tr>
        <?php foreach ($empleados->fetchAll() as $row) { ?>
          <tr>
            <td><?php echo $row['num']; ?></td>
            <td><?php echo $row['first_name']; ?></td>
            <td><?php echo $row['last_name']; ?></td>
            <td><?php echo $row['gender']; ?></td>
            <td><?php echo $row['birth_date']; ?></td>
            <td><?php echo $row['hire_date']; ?></td>
          </tr>
        <?php } ?>
      </table>
    </center>
  </body>
</html>
