<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <center>
    <h3>Portal Empleados Inicio Sesion</h3>
    <form action = "<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method = "post">
      Usuario <input type="text" name="usuario" value=""><br><br>
      Contraseña <input type="text" name="contrasenia" value=""><br><br>
      <input type="submit" name="inicio" value="Iniciar Sesión">
    </form>
  </center>
</body>
</html>
