<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="../css/menu.css">
  </head>
  <body>
    <center>
      <div id="menu">
        <a href="./altaEmpleadoController.php">Alta Empleado</a><br><br>
        <a href="./altaMasivaEmpleadosController.php">Alta Masiva Empleados</a><br><br>
        <a href="./modificarSalarioEmpleadoController.php">Modificar Salario a un empleado</a><br><br>
        <a href="./vidaLaboralController.php">Vida laboral de un empleado</a><br><br>
        <a href="./informacionDepartamentosController.php">Informacion Departamentos</a><br><br>
      </div>
      <br><br><br>
      <a href="../controllers/cerrarSesionController.php">Cerrar Sesión</a>
  </center>
  </body>
</html>
