<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<center>
  <form action = "<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" method = "post">
    Nº Empleado <input type="text" name="numEmpleado" value=""><br><br>
    <input type="submit" name="ver" value="Ver vida laboral">
  </form>
</center>
  </body>
</html>
