<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
  <style>
  table, th, td {
    border:2px solid black;
    border-collapse: collapse;
    padding: 20px;
  }
</style>
</head>
<body>
  <center>
    <table>
      <tr>
        <th>Numero Empleado</th>
        <th>Codigo Departamento</th>
        <th>Fecha Inicio</th>
        <th>Fecha Fin</th>
      </tr>
      <?php foreach ($vidaLaboral->fetchAll() as $row) { ?>
        <tr>
          <td><?php echo $row['emp_no']; ?></td>
          <td><?php echo $row['dept_no']; ?></td>
          <td><?php echo $row['from_date']; ?></td>
          <td><?php echo $row['to_date']; ?></td>
        </tr>
      <?php } ?>
    </table><br><br>
  </center>
</body>
</html>
